# These are supported funding model platforms

github: [Jayshah6699]
patreon: jayshah6633
open_collective: # Replace with a single Open Collective username
ko_fi: jayshah6633
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['paypal.me/jayshah6633']
